### ISSUE TITLE
How to reset the list?

### ISSUE THREAD

**Issue by ozasadnyy** [excogitatr/pagination_view#1]
First of all, thanks for the project!

How can I reset the list (`initialData`)? I do have search input + other filters that I need to apply to the search.
<img src="https://user-images.githubusercontent.com/2954281/73374095-54ae0200-42c2-11ea-9f4e-6340247c4f57.png" width=300/>

Thanks again.

**Comment by vedartm** [comment]
Hi @ozasadnyy, Can you elaborate the issue with sample code? So that it will be easier to understand the problem you are facing.

**Comment by ozasadnyy** [comment]
@excogitatr here is pseudo code:

Model:
```
class ExploreViewModel extends BaseModel {
  final TextEditingController textController = TextEditingController();
  final AppDatabase _db = AppDatabase();
  CocktailFilter filter = CocktailFilter();

  void initModel() {
    textController.addListener(_onTextValueChange);
  }

  void _onTextValueChange() {
    filter.text = textController.text;
  }

  Future<List<Cocktail>> loadCocktails(int offset) {
    return _db.cocktailsDao.filterCocktails(filter, offset: offset);
  }
}

```

View:

```
   PaginationView<Cocktail>(
      pageFetch: model.loadCocktails,
      itemBuilder: (BuildContext context, Cocktail cocktail) => CocktailItem(
        cocktail: cocktail,
      )
    );
```

So what I want to achieve is to force `PaginationView` to invoke `pageFetch` with `offset = 0` when my `filter` changes.

**Comment by vedartm** [comment]
The widget will be forced to use `offset = 0` if the widget is rebuilt when the filter changes. For rebuilding the widget you can add `key` parameter which can be your filter value. Check if this works.
```
  PaginationView<Cocktail>(
    key: Key(model.filter.text)
    pageFetch: model.loadCocktails,
    itemBuilder: (BuildContext context, Cocktail cocktail) => CocktailItem(
      cocktail: cocktail,
    ),
  );
```

**Comment by ozasadnyy** [comment]
It's working. Thanks for help!

**Comment by vishwa-brahmand** [comment]
> The widget will be forced to use `offset = 0` if the widget is rebuilt when the filter changes. For rebuilding the widget you can add `key` parameter which can be your filter value. Check if this works.
> 
> ```
>   PaginationView<Cocktail>(
>     key: Key(model.filter.text)
>     pageFetch: model.loadCocktails,
>     itemBuilder: (BuildContext context, Cocktail cocktail) => CocktailItem(
>       cocktail: cocktail,
>     ),
>   );
> ```

Hi, this solution is working really well. But I have three different values as filter values. How do I use those three filter variables. The key parameter takes only one variable. Can you please help me with this.

**Comment by vedartm** [comment]
You can combine your filters by concatenation as such `Key(filter1+filter2+filter3)`

**Comment by vishwa-brahmand** [comment]
> You can combine your filters by concatenation as such `Key(filter1+filter2+filter3)`

Yup this works. Thanks

**Comment by vishwa-brahmand** [comment]
I am facing another problem, as I have used the filters in the Key() function. I have also added bottomNavigation bar now in the code. So when I change the filter value the list does not updates as it used to be earlier, now once I go to different page from bottomNavigation bar and come back to the main page where my filter is there then it updates the state. 
How can I make this update without moving to other page and make it happen right away.

**Comment by vedartm** [comment]
Can you share the code to get a better understanding of your issue @vishwa-brahmand

**Comment by vishwa-brahmand** [comment]
Hi, so this is my code:-

class LandingPage extends StatefulWidget {
  @override
  _LandingPageState createState() => _LandingPageState();
}

String _currentlySelectedlanguage = "All";

class _LandingPageState extends State<LandingPage> {

  int _currentIndex=0;
  final tabs = [
    ListPage(),
    SearchPage()
  ];

  final List<String> _dropdownValueslanguage = [
    "All"
  ];

  Widget dropdownWidgetlanguage() {
    return DropdownButtonHideUnderline(
      child: DropdownButton(
        style: TextStyle(
            color: Colors.black87,
            fontWeight: FontWeight.bold,
            fontFamily: 'Raleway',
            fontSize: 15),
        isExpanded: false,
        value: _currentlySelectedlanguage,
        onChanged: (String newvalue) {
          setState(() {
            _currentlySelectedlanguage = newvalue;
            print(_currentlySelectedlanguage);
          });
        },
        items: _dropdownValueslanguage
            .map((value) => DropdownMenuItem(
                  child: Text(value),
                  value: value,
                ))
            .toList(),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: new AppBar(
        centerTitle: false,
        title: Text(
          'MoviePass',
          style: TextStyle(
              fontFamily: 'IndieFlower',
              fontWeight: FontWeight.bold,
              fontSize: 22.0),
        ),
        backgroundColor: Colors.orangeAccent,
        actions: <Widget>[
          dropdownWidgetlanguage(),
        ],
      ),
      body: tabs[_currentIndex],
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: _currentIndex,
        items: [
            BottomNavigationBarItem(
              icon: Icon(Icons.home),
              title: Text('Home'),
              backgroundColor: Colors.orangeAccent
              ),
              BottomNavigationBarItem(
              icon: Icon(Icons.search),
              title: Text('Search'),
              backgroundColor: Colors.orangeAccent
              )
       ],
       onTap: (index){
         setState(() {
           _currentIndex = index;
         });
       },
      ),
    );
  }
}

class ListPage extends StatefulWidget {
  @override
  _ListPageState createState() => _ListPageState();
}

class _ListPageState extends State<ListPage> {
  Query getQuery() {
    if (_currentlySelectedlanguage == "All") {
      return Firestore.instance
          .collection('videos')
          .orderBy('rank', descending: true);
    } else {
      return Firestore.instance
          .collection('videos')
          .where("language", isEqualTo: _currentlySelectedlanguage)
          .orderBy('rank', descending: true);
    }
  }



  @override
  Widget build(BuildContext context) {
    return Column(children: <Widget>[
      Expanded(
        child: PaginateFirestore(
          //item builder type is compulsory.
          itemBuilderType:
              PaginateBuilderType.gridView, //Change types accordingly
          itemBuilder: (index, context, documentSnapshot) => Card(
              child: Column(
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  children: [
                InkWell(
                  onTap: () => navigateToDetail(documentSnapshot),
                  child: Image.network(documentSnapshot['imageID']),
                ),
                SizedBox(height: 4.0),
                Text(
                  documentSnapshot['title'],
                  overflow: TextOverflow.ellipsis,
                  style: TextStyle(
                      fontWeight: FontWeight.bold,
                      fontSize: 20,
                      fontFamily: 'IndieFlower'),
                ),
                SizedBox(height: 4.0),
              ])),
          // orderBy is compulsory to enable pagination
          //documentSnapshot['title']
          query: getQuery(),
          key: Key(_currentlySelectedlanguage),
          itemsPerPage: 2,
        ),
      )
    ]);
  }
}



Here I am creating a list to hold different pages which can be navigated through bottom navigation bar. But what is happening is when I click the filter which is dropdown widget it is not updating the list based on the filter value. And when I go to the other page from bottom navigation bar and come back to the main page(where filter is present), then the list updates with the previously selected filter value. There is some delay with the list update when I am using bottom navigation.

**Comment by vishwa-brahmand** [comment]
Hi @excogitatr, I have shared my code above. Can you please look into it.

**Comment by vedartm** [comment]
Hey @vishwa-brahmand. You can't change language and `LandingPage` widget and expect it to change in `ListPage`. You can pass `_currentlySelectedlanguage` variable from `LandingPage` to `ListPage`.
