### ISSUE TITLE
Manual refresh

### ISSUE THREAD

**Issue by paulelpidorou** [excogitatr/pagination_view#11]
Hey great package love it!

Quick question. Is there a way to manually trigger a refresh of the list? for example to load from page 1 again?

Thanks

**Comment by vedartm** [comment]
Glad you loved it @paulelpidorou. You can refresh the pagination simply by changing the `key` of the widget. Refer this issue #1 

Feel free to reopen the issue if you face similar problem

**Comment by paulelpidorou** [comment]
Works like a charm! 😄 Thanks
