### ISSUE TITLE
Refresh feature

### ISSUE THREAD

**Issue by jezsung** [excogitatr/pagination_view#12]
If there's somehow refresh the list, it will be perfect

**Comment by vedartm** [comment]
You can manually refresh it by changing the key of the `PaginationView` widget like should in this issue #1 . I will add a swipe to refresh feature in the next update. Hope this helps solve the issue for now.

**Comment by avvari-da** [comment]
@excogitatr Can you please add the feature's usage to documentation? I see that it is now added to the latest release
