### ISSUE TITLE
Some question and suggestion regarding the usecase of pagination_view.

### ISSUE THREAD

**Issue by 1207roy** [excogitatr/pagination_view#17]
1. what if I don't want to fetch the new list(pageFetch call) in some condition?
Currently, if I return the empty list for these types of conditions, then it stopped calling the pageFetch
method for future cases where actually I needed to load the upcoming list items.

2. Suggestion: 
preloadedItems should handles the result which can be a future (can be fetched from network).
Or it should by default take an empty list if not provided preLaodItems, and handles the new update from pageFetch.

**Comment by vedartm** [comment]
1. Sending an empty list when your condition is met in `pageFetch` is the current best solution.
2. This is can be done in the future update. But for now you can preload a list with `[null]` and check for null in itemBuilder and use a `FutureBuilder` to preload items in the null case.

**Comment by vedartm** [comment]
Hope this solves your issues. Feel free to reopen this if you face any similar issues. Thanks for using the package.
