### ISSUE TITLE
[Feature Request]-Scroll Controller Availabilty

### ISSUE THREAD

**Issue by ariefwijaya** [excogitatr/pagination_view#18]
Is it possible to inject our scroll controller to Pagination_View widget and listen or use it to the listener?

**Comment by vedartm** [comment]
It can be added in the next version @ariefwijaya

**Comment by ariefwijaya** [comment]
Ok thank you, I will mark this as closed

**Comment by vedartm** [comment]
It is now available in v1.0.3 🎉

**Comment by ariefwijaya** [comment]
Good News, Thank you
