### ISSUE TITLE
[Feature Request] PaginationView inside CustomScrollView

### ISSUE THREAD

**Issue by ariefwijaya** [excogitatr/pagination_view#22]
I think, it might be useful paginationView inside CustomScrollView.
What do you think?

Thanks

**Comment by vedartm** [comment]
You can add PaginationView inside any srcoll view by setting the attribute `shrinkWrap` to true. It is similar to adding a listview inside another listview

**Comment by ariefwijaya** [comment]
I've tried but it didnt worked. CustomScrollView need sliver inside. so , you need add optional to return PaginationView as a SliverList or SliverGrid instead of ListView or GridView.

**Comment by vedartm** [comment]
@ariefwijaya Did you try it inside `SliverFillRemaining`?

**Comment by kaiserleka** [comment]
initialLoader

**Comment by vedartm** [comment]
Now pagination view supports `header` and `footer`. With this you can add any widget to add on top of your pagination view. Hope this solves you issue @ariefwijaya

**Comment by denis-isaev** [comment]
> Now pagination view supports `header` and `footer`. With this you can add any widget to add on top of your pagination view. Hope this solves you issue @ariefwijaya

This won't help if we need an expanded SliverAppBar.

**Comment by mtiziano** [comment]
https://github.com/excogitatr/pagination_view/blob/29e1932da55c02c18018a69f2fa43014e57af05f/lib/pagination_view.dart#L123

just don't wrap header with sliver, so you can decide to use **SliverAppBar** or **SliverToBoxAdapter**

**Comment by vedartm** [comment]
@mtiziano @denis-isaev pagination_view v2.0.0 now supports sliver 🎉. You can add `SliverAppBar` for a sticky header and `SliverFillRemaining` for a sticky footer.
