### ISSUE TITLE
Custom pull to refresh widget UI

### ISSUE THREAD

**Issue by victorkiver** [excogitatr/pagination_view#25]
Thanks for the awesome library! But I can't find how to use custom pull to refresh widget. Can you help me pls?

**Comment by vedartm** [comment]
Hey @victorkiver. Thanks for using the package. Check the file [example.dart](https://github.com/excogitatr/pagination_view/blob/master/example/lib/main.dart) to get a clear picture.

**Comment by vedartm** [comment]
Hope this fixed your issue. Feel free to reopen if you face any similar issue
