### ISSUE TITLE
automatically execute pageFetch function until get all data

### ISSUE THREAD

**Issue by rozone** [excogitatr/pagination_view#26]
Thanks for the awesome widget;
but when I try it inside the SliverToBoxAdapter, it automatically execute pageFetch function until get all data;
the same when put it in another ListView, shrinkWrap is set true.

**Comment by vedartm** [comment]
Now pagination_view (v1.0.4) supports `header` and `footer`. With this you can add any widgets you want to display above pagination view as header. Hope this fixes the issue. Feel free to reopen it if you face a similar issue.

**Comment by ayaanpathan** [comment]
I'm facing this issue, my pagination is inside a column.

**Comment by vedartm** [comment]
@ayaanpathan Try not to put pagination inside a column, instead use `header` and `footer`. If you have to, then make sure it is wrapped with expanded.

**Comment by ayaanpathan** [comment]
Tried this but doesn't work. It still auto loads the data. It works properly in a screen where there is only the pagination. It doesn't work well with the other widgets, even after wrapping it with the Expanded

**Comment by ayaanpathan** [comment]
Had to re design my whole home page based on header and footer. It's working now. Thanks!!
