### ISSUE TITLE
bottomLoader visible if list is short

### ISSUE THREAD

**Issue by emrade** [excogitatr/pagination_view#3]
Hello, I was trying to implement this package and I noticed that when I fetch data from an API and the number of data returned is not enough to cover the whole view or enough to have it scroll, it causes the bottomLoader to maintain its visibility.
Can you help me, please?

Here is a screenshot
![Screenshot_3](https://user-images.githubusercontent.com/25217766/80265169-243df000-8686-11ea-9001-d835723d6732.png)

**Comment by vedartm** [comment]
Hey @emrade try switching to v0.7.0 for now. I am fixing the issue right away

**Comment by emrade** [comment]
Thanks a lot for the quick response. I will do that.

**Comment by vedartm** [comment]
Fixed it. Check out the version 1.0.1+1
I am closing the issue now. If you face any problem related to this, feel free to reopen.
And thanks for using the package. Hope you liked it 🎉

**Comment by emrade** [comment]
Thanks a lot. It works perfectly well now. And yes I really love the package, it has everything I need.
