### ISSUE TITLE
Show PaginationView header or footer always

### ISSUE THREAD

**Issue by ashishbharwal001** [excogitatr/pagination_view#30]
Hi thank you for the awesome library. But can you provide a way to always show header and footer even when the data is blank i.e with "onEmpty:"  widget.

As am using date picker as a filter for the list so when I change date then it should refresh the list and add new data but instead it add the data in the existing list. So please profile a way to clear the list other than pull to refresh method.

**Comment by vedartm** [comment]
Thanks for using the package @ashishbharwal001 .

For persistent header and footer, the immediate solution is to use it inside a column. Like this,
```dart
Column(
    children: [
        Header(),
        Expanded(child: PaginationView(...)),
        Footer(),
    ]
)
```

For the custom refresh, you can refer the example [main.dart](https://github.com/excogitatr/pagination_view/blob/master/example/lib/main.dart) and use `key.currentState.refresh()`

**Comment by vedartm** [comment]
I hope this fixed your issue. Feel free to reopen it if you face any similar issues.
