### ISSUE TITLE
Loader Alignment in GridView

### ISSUE THREAD

**Issue by morphoes** [excogitatr/pagination_view#31]
Hello.

First of all, I use Pagination_view very useful, and I am always grateful to the producer.

I want to know how align to center in GridView. ex) 2 columns in a row.

If I construct two columns in one line, at PageFetch, Loader always aligns to the left.

If you have a solution please let me know.
Thank you.

![Simulator Screen Shot - iPhone 12 Pro - 2021-02-08 at 12 33 07](https://user-images.githubusercontent.com/27759183/107172893-d40ffe80-6a09-11eb-9c40-b36effbd7b70.png)

**Comment by vedartm** [comment]
Hey @snaphers Thanks for using the package. Can you share some code sample so that we get a clear picture of the problem?

**Comment by OverLoadedBurden** [comment]
> If I construct two columns in one line, at PageFetch, Loader always aligns to the left.

faced the same limitation but i was able to bypass it by using `FractionalTranslation`  like :

```
FractionalTranslation(
    translation: Offset(-.5, 0),
    child: _loader,
  )
```

> I want to know how align to center in GridView. ex) 2 columns in a row.


you may control the horizontal alignment if columns incremented by dividing the columns count by 2 and subtract the loader column number in the grid.

**Comment by vedartm** [comment]
Hope this fixes your issue @snaphers. Feel free to reopen if you face any similar issues. Thanks for using the package 🎉
