### ISSUE TITLE
depends error in this version pagination_view: ^1.0.4+2

### ISSUE THREAD

**Issue by panjt1995** [excogitatr/pagination_view#34]
could you please help me to solving this problem
thank you very much

Running "flutter pub get" in projectTest...                        
Because pagination_view >=1.0.4+2 <2.0.0-nullsafety.0 depends on flutter_bloc ^6.1.3 which depends on provider ^4.3.3, pagination_view >=1.0.4+2 <2.0.0-nullsafety.0 requires provider ^4.3.3.

So, because projectTest depends on both provider ^5.0.0 and pagination_view ^1.0.4+2, version solving failed.
pub get failed (1; So, because projectTest depends on both provider ^5.0.0 and pagination_view ^1.0.4+2, version solving failed.)
--

**Comment by vedartm** [comment]
If you are using bloc package as well, then update it to the version `^6.1.3`
```yaml
  bloc: ^6.1.3
  flutter_bloc: ^6.1.3
```

**Comment by panjt1995** [comment]
> If you are using bloc package as well, then update it to the version `^6.1.3`
> 
> ```yaml
>   bloc: ^6.1.3
>   flutter_bloc: ^6.1.3
> ```

ok thank you very much

**Comment by vedartm** [comment]
Hope this solved your issue. Thanks for using the package.
