### ISSUE TITLE
refresh programmatically 

### ISSUE THREAD

**Issue by smunozp** [excogitatr/pagination_view#36]
There is any way to refresh a PaginatedView programmatically ?

I'm have the pagination_view widget and a form on the same page. When the form is submitted, I need to refetch, to update the list I'm showing with PaginatedView

Thanks

**Comment by vedartm** [comment]
Thanks for using the package @smunozp. This can be added in the next release

**Comment by LostInDarkMath** [comment]
Yes, that would be a very nice feature. Because I need the possibility to discard the whole list and load from scratch when the user changes one of the filters my app provide.

**Comment by LostInDarkMath** [comment]
Oh, I just found out that my problem is the exact same as in https://github.com/excogitatr/pagination_view/issues/1. And that solution works for me. Thanks.

**Comment by mtiziano** [comment]
at the moment, with 
`GlobalKey<PaginationViewState> paginationKey = GlobalKey()`
you can
`PaginationView<T>(
      key: paginationKey,`
      and then
      `paginationKey.currentState.refresh()`

--      
it works, but not showing **loaders** or **RefreshIndicator**

**Comment by NikhilMJain** [comment]
One way to do it is to use a key and change its value programatically to trigger a widget rebuild.

```
class ExampleWidget extends StatefulWidget {
  @override
  _ExampleWidgetState createState() => _ExampleWidgetState();
}

class _ExampleWidgetState extends State<ExampleWidget> {
  String _paginationViewKey = Uuid().v4();

  Future<List<MyModel>> _pageFetchFunc(offset) {}

  @override
  Widget build(BuildContext context) {
    return PaginationView<MyModel>(
      key: Key(_paginationViewKey),
      onError: (dynamic error) {
        return OutlinedButton(
          child: Text('REFRESH'),
          onPressed: () {
            setState(() {
              _paginationViewKey = Uuid().v4();
            });
          },
        );
      },
      pageFetch: _pageFetchFunc,
      itemBuilder: (BuildContext context, DealPost post, int index) {},
    );
  }
}
```

You have to change the value of `key` to trigger a full rebuild when `setState` is called.

You can use an incrementor or a random string generator. I have used `Uuid` to generate random string. Just make sure the string you assign is different from the already existing `_paginationViewKey` value.

**Comment by smunozp** [comment]
thanks for the tip, other question, dont kow if here is correct or open another issue, there will be useful if on the pageFetchFunc be able to pass more parameters either than only offset so I can filter on the backend, to be able to do something like:
`      pageFetch: _pageFetchFunc(filterParams),
`

**Comment by vedartm** [comment]
Hey @smunozp. I think it's better if we create a new issue. I am closing this now and feel free to open this if you face any similar issues.
