### ISSUE TITLE
Refresh Loader

### ISSUE THREAD

**Issue by SPMXithing** [excogitatr/pagination_view#37]
I see no option to provide the type of refresh loader that you get. Do you see a possibility to implement that? It would be perfect if we could customise our own loaders for the bottom and top. 
Now we can only do it for the initial and the bottom but the refresh one is a different animation.

**Comment by vedartm** [comment]
Hey @SPMXithing! Do you mean the animation for pull to refresh? If so, you can check this [comment](https://github.com/excogitatr/pagination_view/issues/36#issuecomment-830043063) in a previous issue and implement your own refresh mechanism.

**Comment by vedartm** [comment]
Hope you are not facing this issue anymore. Feel free to reopen this if you face any similar issues. Thanks for using the package.
