### ISSUE TITLE
Pagination view doesn't update with new list data unless i swipe down refresh

### ISSUE THREAD

**Issue by Ozak93** [excogitatr/pagination_view#41]
Hello, am having a frustrating problem with Pagination View, am retrieving list of movies from my API and displaying them in my pagination view, the data is retrieved in a ChangNotifier class and the pagination view widget is wrapped in a consumer, but the pagination view doesn't load the new data when they arrive, unless i pull down refresh.

this is a video demo to better describe my problem https://streamable.com/ca8k8g

I apologize if am making a rookie mistake, am learning flutter and i may have missed a pretty obvious step to setting up this function.

**Comment by vedartm** [comment]
Hey @Ozak93! Thanks for using the package. I am not able to open that streamable link you mentioned. It will be helpful to better understand your problem if you can share some code samples.

**Comment by Ozak93** [comment]
oh am sorry, how about now ?

https://user-images.githubusercontent.com/31257994/118519453-cf15c600-b741-11eb-8107-af591a187dad.mp4


Here's my code, just an app bar with a search widget and the pagination view in a consumer.
 ```
class MoviesPage extends StatelessWidget {
  final ApiProvider apiProvider = ApiProvider();

  final TextEditingController searchQueryController = TextEditingController();

  String q = "";

  @override
  Widget build(BuildContext context) {
    bool isSearching = false;
    return Consumer<ApiProvider>(
      builder: (context, provider, child) => Scaffold(
        appBar: AppBarTextField(
          title: Text("Movies List"),
          autofocus: false,
          controller: searchQueryController,
          onSubmitted: (query) {
            if (query.length > 2) provider.setQuery(searchQueryController.text);
          },
          onClearPressed: () {
            apiProvider.setQuery("");
          },
        ),
        body: Container(
          child: Center(
              child: paginationWidget(
            provider: provider,
          )),
        ),
      ),
    );
  }
}

class paginationWidget extends StatelessWidget {
  final ApiProvider provider;
  const paginationWidget({required this.provider});

  @override
  Widget build(BuildContext context) {
    return PaginationView<Movie>(
      scrollController: provider.pageScrollController,
      pullToRefresh: true,
      pageFetch: (currentListSize) => provider.fetchMovies(),
      itemBuilder: (ctx, mov, idx) => MovieCard(obj: mov),
      paginationViewType: PaginationViewType.listView,
      bottomLoader: Center(
        child: CircularProgressIndicator(
          color: Colors.blue,
        ),
      ),
      onEmpty: Center(
        child: Text(
          "there's no more movies to show !",
        ),
      ),
      onError: (err) {
        return Center(child: Text("error: $err"));
      },
    );
  }
}

```


for my Fetch function, which is in my provider: 

```

  Future<List<Movie>> fetchMovies({int page = 1, String q = ""}) async {
    var res;

    if (searchQuery.trim() != "") {
      res = await http.get(Uri.parse(
          'mylink?quality=720p,1080p&query_term=$searchQuery&sort_by=download_count'));
      print("search query is $searchQuery");
    } else
      res = await http.get(Uri.parse(
          'mylink?quality=720p,1080p&sort_by=download_count&page=$currentPage'));

    if (res.statusCode == 200) {
      Movieinfo x = movieinfoFromJson(res.body);
      print("################### $page");

      currentPage++;
      movies = x.data.movies;

    
     notifyListeners();
      return movies;
     
    } 

```

**Comment by vedartm** [comment]
I guess you have to refresh the `key` of PaginationView in `onSubmitted` callback. Also what does this function do `provider.setQuery(searchQueryController.text);`?

**Comment by Ozak93** [comment]
Setquery just updates the search term's value in my provider and notifies listeners, i tried streams with it but it didnt work 

```

  void setQuery(String q) async {
    searchSink.add(q);

    searchQuery = q;
    fetchMovies(q: q);
    notifyListeners();
  }

```

am not sure what do you mean by refresh key ? i just want the view to update as soon as it receives data when i submit (The data retrieves successfully)

**Comment by Ozak93** [comment]
> I guess you have to refresh the `key` of PaginationView in `onSubmitted` callback. Also what does this function do `provider.setQuery(searchQueryController.text);`?

i checked the example provided in the package's pub dev page, i used key.currentState.refresh() in setquery and onclearpressed and the view successfully reloads with the new data ! thank you @excogitatr for your help !
