### ISSUE TITLE
RenderSliver issue

### ISSUE THREAD

**Issue by ayaanpathan** [excogitatr/pagination_view#44]
I have the main UI code which starts from header and the main parent is a gesture Detector widget.  After updating to the latest null safety version, I am getting the below error:

`The following assertion was thrown building NotificationListener<ScrollNotification>:
A RenderShrinkWrappingViewport expected a child of type RenderSliver but received a child of type
RenderRepaintBoundary.
RenderObjects expect specific types of children because they coordinate with their children during
layout and paint. For example, a RenderSliver cannot be the child of a RenderBox because a
RenderSliver does not understand the RenderBox layout protocol.
The RenderShrinkWrappingViewport that expected a RenderSliver child was created by:
  ShrinkWrappingViewport ← IgnorePointer-[GlobalKey#58bb2] ← Semantics ← Listener ←
  _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#b659b] ←
  Listener ← _ScrollableScope ← _ScrollSemantics-[GlobalKey#4bfcf] ← RepaintBoundary ← CustomPaint ←
  RepaintBoundary ← ⋯
The RenderRepaintBoundary that did not match the expected child type was created by:
  RepaintBoundary ← NotificationListener<ScrollNotification> ← GlowingOverscrollIndicator ←
  Scrollable ← PrimaryScrollController ← SingleChildScrollView ← ShrinkWrappingViewport ←
  IgnorePointer-[GlobalKey#58bb2] ← Semantics ← Listener ← _GestureSemantics ←
  RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#b659b] ← ⋯`

**Comment by anggaaryas** [comment]
Are you using header / footer without using silver?

**Comment by vedartm** [comment]
@ayaanpathan can you share some code samples to better understand your issue?

**Comment by ayaanpathan** [comment]
> Are you using header / footer without using silver?

yes

**Comment by ayaanpathan** [comment]
> @ayaanpathan can you share some code samples to better understand your issue?

`PaginationView<User>(
                key: key,
                preloadedItems: <User>[
                  User(faker.person.name(), faker.internet.email()),
                  User(faker.person.name(), faker.internet.email()),
                ],
                paginationViewType: paginationViewType,
                itemBuilder: (BuildContext context, User user, int index) {
                  List<String> categoryList = List<String>();
                  categoryList.clear();
                  for (int i = 0;
                  i <
                      moreRestaurantsMap['data'][index]['categories']
                          .length;
                  i++) {
                    categoryList.add(moreRestaurantsMap['data'][index]
                    ['categories'][i]['name']);
                  }
                  print(categoryList.toString());
                  return MoreRestaurantsItem(
                    restaurantId: moreRestaurantsMap['data'][index]['id'],
                    image: moreRestaurantsMap['data'][index]['images'][0]
                    ['url'],
                    title: moreRestaurantsMap['data'][index]['name'],
                    // category: 'Categories',
                    index: index,
                    category: categoryList
                        .toString()
                        .replaceAll("[", "")
                        .replaceAll("]", ""),
                    map: moreRestaurantsMap,
                    location: moreRestaurantsMap['data'][index]['address'],
                    discount: moreRestaurantsMap['data'][index]['discount'],
                    rating:
                    moreRestaurantsMap['data'][index]['rating'].toString(),
                    isFavorite: favouriteId.contains(
                        moreRestaurantsMap['data'][index]['id']),
                    onIsFavouritePress: (val) {
                      if (favouriteId.contains(val)) {
                        favouriteId.remove(val);
                      } else {
                        favouriteId.add(val);
                      }
                    },
                    delivery: moreRestaurantsMap['data'][index]
                    ['delivery_available'],
                  );
                },
                pageFetch: pageFetch,
                header:
                GestureDetector(
                  onTap: () {
                    FocusScope.of(context).requestFocus(new FocusNode());
                  },
                  child: SingleChildScrollView(
                    physics: BouncingScrollPhysics(),
                    child: Stack(
                      children: <Widget>[
                        _background,
                        // _appBar,
                        Align(
                          alignment: Alignment.centerRight,
                          child: Padding(
                            padding: const EdgeInsets.only(
                                top: 47.0, left: 10.0, right: 0),
                            child: Row(
                                mainAxisAlignment:
                                MainAxisAlignment.spaceBetween,
                                children: <Widget>[
                                  Expanded(
                                    child: Container(
                                      width: MediaQuery
                                          .of(context)
                                          .size
                                          .width,
                                      child: Row(
                                        mainAxisAlignment: MainAxisAlignment
                                            .start,
                                        children: [
                                          Padding(
                                            padding: const EdgeInsets.only(
                                                bottom: 6.0, right: 8),
                                            child: Icon(
                                              Icons.location_on_rounded,
                                              size: 25,
                                              color: Colors.white,
                                            ),
                                          ),
                                          GestureDetector(
                                              onTap: () {
                                                FocusManager.instance
                                                    .primaryFocus?.unfocus();
                                                _editDeliveryLocationModalSheet(
                                                    context);
                                              },
                                              child: //currentPosition != null &&
                                                  currentLocation == null || currentLocation ==''
                                                  ? Text(
                                                'Current Location',
                                                style: TextStyle(
                                                    fontFamily: "Sofia",
                                                    fontSize: 14,
                                                    // letterSpacing: 1.5,
                                                    color: Colors.white),

                                              )
                                                : Container(
                                                width: 360.0,
                                                child: Text(
                                                  currentLocation,
                                                  overflow: TextOverflow
                                                      .ellipsis,
                                                  style: TextStyle(
                                                      fontFamily: "Sofia",
                                                      fontSize: 14,
                                                      // letterSpacing: 1.5,
                                                      color: Colors.white),
                                                ),
                                              )
                                                   ),
                                        ],
                                      ),
                                    ),
                                  ),
                                ]),
                          ),
                        ),
                        _body,
                      ],
                    ),
                  ),
                ),
                shrinkWrap: true,
                physics: BouncingScrollPhysics(),
                pullToRefresh: true,
                onError: (dynamic error) =>
                    Center(
                      child: Text('Some error occured'),
                    ),
                onEmpty: Center(
                  child: Text('Sorry! This is empty'),
                ),
                bottomLoader: Center(
                  child: Padding(
                    padding: const EdgeInsets.only(top: 20.0),
                    child: CircularProgressIndicator(
                      valueColor:
                      AlwaysStoppedAnimation<Color>(Constants.mfaRed),
                    ),
                  ),
                ),
                initialLoader: Center(
                  child: CircularProgressIndicator(
                    valueColor: AlwaysStoppedAnimation<Color>(Constants.mfaRed),
                  ),
                ),
              )`

**Comment by vedartm** [comment]
Wrap the `GestureDetector` in the header with `SliverToBoxAdapter` this should fix your issue.

**Comment by ayaanpathan** [comment]
This solved my issue. Thanks!
