### ISSUE TITLE
PageFetch Logic. 

### ISSUE THREAD

**Issue by ayaanpathan** [excogitatr/pagination_view#45]
Hi. Can anyone help me with pagefetch logic, below is my code for the current pagefetch logic. 
Currently the page number is set as static but i want it to return an empty list on the last page of my Map's length. 

**PageFetch:**
`Future<List<User>> pageFetch(int offset) async {
    print(offset);
    print(moreRestaurantsMap['data'].length);
    page = (offset / 4).round();
    final Faker faker = Faker();
    final List<User> nextUsersList = List.generate(
      5,
      (int index) => User(
        faker.person.name() + ' - $page$index',
        faker.internet.email(),
      ),
    );
    await Future<List<User>>.delayed(Duration(seconds: 1));
    return page == 24 ? [] : nextUsersList;
  }`

Below is the error I receive 
![image](https://user-images.githubusercontent.com/48903105/122345114-1b347000-cf65-11eb-9806-c2f013fb8fef.png)

Total number of restaurants at the backend is 104 but it should not matter as pagefetch should be dynamic and should be able to handle the length properly

**Comment by vedartm** [comment]
Hi @ayaanpathan. Thanks for using the package. 
How many items are you trying to fetch in a page? Is it 4?

**Comment by ayaanpathan** [comment]
5

**Comment by vedartm** [comment]
In that case, it should be `offset / 5` right? Also, the above code you mentioned does not look like the function you are actually using. Can you share the actual code to get a clear picture?

**Comment by ayaanpathan** [comment]
Sure.  This is the code. 

` Future<List<User>> pageFetch(int offset) async {
    print(offset);
    print(moreRestaurantsMap['data'].length);
    print((moreRestaurantsMap['data'].length / 5).round());
    print((offset / 5).round());
    page = (offset / 5).round();
    final Faker faker = Faker();
    final List<User> nextUsersList = List.generate(
      page == (moreRestaurantsMap['data'].length / 5).round() ? 2 :
      5,
          (int index) =>
          User(
            faker.person.name() + ' - $page$index',
            faker.internet.email(),
          ),
    );
    await Future<List<User>>.delayed(Duration(seconds: 1));
    return page == (moreRestaurantsMap['data'].length / 5).round()
        ? []
        : nextUsersList;
  }`

**Comment by ayaanpathan** [comment]
This is my API code

`Future<void> getMoreRestaurants(int offset) async {
    var formData = 
    //currentPosition == null ? 
    FormData.fromMap({
      'limit': 10000,
      'offset': offset,
      'order': 'distance',
      'sort': 'asc',
    });
    try {
      response =
      await dio.post(Config.moreRestaurants,
          data: formData,
          options: Options(headers: {'Authorization': 'Bearer $authToken'}));

      setState(() {});
      moreRestaurantsMap = json.decode(response.toString());
      print(moreRestaurantsMap);
      print(featuredMap['meta']['count']);
      print(moreRestaurantsMap['meta']['count']);
      restaurantTotal =
          featuredMap['meta']['count'] + moreRestaurantsMap['meta']['count'];
      setState(() {

      });
      moreRestaurantsMapData = moreRestaurantsMap['data'];
      for (var x in moreRestaurantsMap['data']) {
        if (x['favourite']) {
          favouriteId.add(x['id']);
        }
      }
      setState(() {
        loadMoreRestaurants = false;
        // loadFeaturedImage = true;
      });

      // closeProgressDialog(context);
    } on DioError catch (e) {
      // The request was made and the server responded with a status code
      // that falls out of the range of 2xx and is also not 304.
      // closeProgressDialog(context);
      if (e.response != null) {
        print(e.response.data);
        print(e.response.headers);
        print(e.response.request);
        print("This is the error message::::" +
            e.response.data['meta']['message']);
        Fluttertoast.showToast(
          msg: e.response.data['meta']['message'],
          toastLength: Toast.LENGTH_SHORT,
          gravity: ToastGravity.BOTTOM,
          timeInSecForIosWeb: 1,
          backgroundColor: Color(0xFF1E2026),
          textColor: Constants.mfaRed,
          fontSize: 15,
        );
      } else {
        // Something happened in setting up or sending the request that triggered an Error
        print(e.request);
        print(e.message);
      }
    }
  }`

**Comment by vedartm** [comment]
>var formData =
//currentPosition == null ?
FormData.fromMap({
'limit': 10000,
'offset': offset,
'order': 'distance',
'sort': 'asc',
});

I think the problem is with the `limit` here. Set it to 5 or any number less than 104. This should work.

**Comment by ayaanpathan** [comment]
Sure. Let me try that

**Comment by ayaanpathan** [comment]
Thanks @vedartm I tweaked the code and made proper changes suggested by you and it's working perfectly fine now. One more thing I wanted to ask was that how do I remove the initial loader which comes before rendering all the widgets?

**Comment by ayaanpathan** [comment]
I have a shimmer on the home screen as a loader so I wanted to remove the initial loader, is there any way to disable it?

**Comment by vedartm** [comment]
Hi @ayaanpathan. Initial loader is just a widget. You pass an empty `SizedBox()` or `Container()`

**Comment by ayaanpathan** [comment]
Thanks. I am closing this issue now. Thanks a lot for your help and for an amazing package!
