### ISSUE TITLE
when I add header or footer not type of  RenderSliver  

### ISSUE THREAD

**Issue by emadjoha** [excogitatr/pagination_view#47]
A RenderViewport expected a child of type RenderSliver but received a child of type RenderParagraph.
I'm using flutter version 2.0.2 and pagination_view 2.0.0

my code like example in pub site: 

     PaginationView<User>(
        itemBuilder: (BuildContext context, User user, int index) => ListTile(
          title: Text(user.name),
          subtitle: Text(user.email),
          leading: IconButton(
            icon: Icon(Icons.person),
            onPressed: () => null,
          ),
        ),
        header: Text('Header text'),
        footer: Text('Footer text'),
        paginationViewType: PaginationViewType.listView // optional
        pageFetch: pageFetch,
        onError: (dynamic error) => Center(
          child: Text('Some error occured'),
        ),
        onEmpty: Center(
          child: Text('Sorry! This is empty'),
        ),
        bottomLoader: Center( // optional
          child: CircularProgressIndicator(),
        ),
        initialLoader: Center( // optional
          child: CircularProgressIndicator(),
        ),
      ),

**Comment by vedartm** [comment]
From the version 2.0.0, we need to wrap the `header` and `footer` with a Sliver. For example,
```dart
header: SliverToBoxAdapter(child: Text('Header text'))
```

**Comment by emadjoha** [comment]
thank you for reply me dear , please keep  pub.dev Site  up to date
