### ISSUE TITLE
pagefetch method is called multiple times at once

### ISSUE THREAD

**Issue by ayaanpathan** [excogitatr/pagination_view#49]
Hi. When i try to scroll down, the pagefetch method gets called multiple times and the backend gets throttled. Is there any way to hit the method only once?

**Comment by ayaanpathan** [comment]
Below is my code for reference. 

` Future<List<RestaurantDetails>> pageFetchWithLocation(int offset) async {
    print(offset);
    await getMoreRestaurantsWithLocation(offset,  moreLat, moreLng);
    print((offset / 10).round());
    page = (offset / 10).round();
    final List<RestaurantDetails> nextUsersList = List.generate(
      moreRestaurantsMap['data'].length < 10 ? moreRestaurantsMap['data'].length : 10,
          (int index) =>
          RestaurantDetails(
            image: moreRestaurantsMap['data'][index]['images'].length == 0 ? "https://image.shutterstock.com/image-vector/illustration-restaurant-facade-tables-chairs-600w-131451491.jpg" : moreRestaurantsMap['data'][index]['images'][0]
            ['url'],
            title: moreRestaurantsMap['data'][index]['name'],
            // category: 'Categories',
            index: index,
            category: moreRestaurantsMap['data'][index]['categories']
                .toString()
                .replaceAll("[", "")
                .replaceAll("]", ""),
            phoneNumber: moreRestaurantsMap['data'][index]['contact'],
            timingsList: moreRestaurantsMap['data'][index]['timings'],
            isSubscribed: moreRestaurantsMap['data'][index]['is_subscribe'],
            doesDelivery: moreRestaurantsMap['data'][index]['delivery_available'],
            description: moreRestaurantsMap['data'][index]['description'],
            isOpen: moreRestaurantsMap['data'][index]['current_day'][0]['is_open'],
            id: moreRestaurantsMap['data'][index]['id'],
            restaurantId: moreRestaurantsMap['data'][index]['restaurant_id'],
            price: moreRestaurantsMap['data'][index]['name'],
            ratingCount: moreRestaurantsMap['data'][index]['rating_count'].toString(),
            lat: moreRestaurantsMap['data'][index]['lat'],
            lng: moreRestaurantsMap['data'][index]['lng'],
            igtv: moreRestaurantsMap['data'][index]['igtv'],
            imageList: moreRestaurantsMap['data'][index]['images'],
            categoryList: moreRestaurantsMap['data'][index]['categories'],
            map: moreRestaurantsMap,
            location: moreRestaurantsMap['data'][index]['address'],
            discount: moreRestaurantsMap['data'][index]['discount'],
            rating:
            moreRestaurantsMap['data'][index]['rating'].toString(),
            isFavorite: favouriteId.contains(
                moreRestaurantsMap['data'][index]['id']),
            onIsFavouritePress: (val) {
              if (favouriteId.contains(val)) {
                favouriteId.remove(val);
              } else {
                favouriteId.add(val);
              }
            },
            delivery: moreRestaurantsMap['data'][index]
            ['delivery_available'],
          ),
    );
    await Future<List<RestaurantDetails>>.delayed(Duration(seconds: 1));
    isMoreListLoading = true;
    return moreRestaurantsMap['data'] == []
        ? []
        : nextUsersList;

  }`

**Comment by ayaanpathan** [comment]
Hi @vedartm any suggestion?

**Comment by vedartm** [comment]
Can you tell exactly how many times more it is calling @ayaanpathan. From what I have seen, it will make only one additional call just to make sure it returns an empty list. That empty list is the indicator for the package to stop paginating.

**Comment by ayaanpathan** [comment]
It calls about 6 times on one load. So if I do brute force load then it
requests about 100 times or so in a matter of seconds hence throttling
kicks in for laravel and it stops the user from making more requests

**Comment by ayaanpathan** [comment]
Hi @vedartm any suggestions?

**Comment by vedartm** [comment]
Can you share how you are using the widget? If it is inside another list view or something this might happen.

**Comment by ayaanpathan** [comment]
Sure. Below is my code. Please excuse me for not formatting properly. 

` return GestureDetector(
      onTap: () {
        //FocusManager.instance.primaryFocus?.unfocus();
      },
      child: RefreshIndicator(
          onRefresh: _refreshLists,
          backgroundColor: Color(0xFF1E2026),
          color: Constants.mfaRed,
          child: WillPopScope(onWillPop: () async => false,
            child: Scaffold(
              backgroundColor: Color(0xFF1E2026),
              body:
              loadMoreRestaurants
                  ? ListView(
                shrinkWrap: true,
                children: [
                  SizedBox(height: 45),
                  _loadingFeaturedImageCarousel(context),
                  SizedBox(height: 15),
                  Container(
                      height: 80, child: _loadingBrowseByCuisineList(context)),
                  // _loadingImageAnimationDiscount(context),
                  _loadingMoreRestaurantsList(context),
                ],
              )
                  :
              isSearching
                  ? SingleChildScrollView(
                physics: BouncingScrollPhysics(),
                child: Container(
                  // height: MediaQuery.of(context).size.height,
                    child: Stack(
                      children: [
                        _background,
                        Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: <Widget>[

                            Align(
                              alignment: Alignment.centerRight,
                              child: Padding(
                                padding: const EdgeInsets.only(
                                    top: 47.0, left: 10.0, right: 0),
                                child: Row(
                                    mainAxisAlignment:
                                    MainAxisAlignment.spaceBetween,
                                    children: <Widget>[
                                      Expanded(
                                        child: Container(
                                          width: MediaQuery
                                              .of(context)
                                              .size
                                              .width,
                                          child: Row(
                                            mainAxisAlignment: MainAxisAlignment
                                                .start,
                                            children: [
                                              Padding(
                                                padding: const EdgeInsets.only(
                                                    bottom: 6.0, right: 8),
                                                child: Icon(
                                                  Icons.location_on_rounded,
                                                  size: 25,
                                                  color: Colors.white,
                                                ),
                                              ),
                                              GestureDetector(
                                                  onTap: () {
                                                    _editDeliveryLocationModalSheet(
                                                        context);
                                                  },
                                                  child: currentPosition !=
                                                      null &&
                                                      currentLocation != null ||
                                                      currentPosition != null &&
                                                          currentLocation != ''
                                                      ? Container(
                                                    width: 360.0,
                                                    child: Text(
                                                      currentLocation,
                                                      overflow: TextOverflow
                                                          .ellipsis,
                                                      style: TextStyle(
                                                          fontFamily: "Sofia",
                                                          fontSize: 14,
                                                          // letterSpacing: 1.5,
                                                          color: Colors.white),
                                                    ),
                                                  )
                                                      : Text(
                                                    'Set Your Location',
                                                    style: TextStyle(
                                                        fontFamily: "Sofia",
                                                        fontSize: 14,
                                                        // letterSpacing: 1.5,
                                                        color: Colors.white),

                                                  )),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ]),
                              ),
                            ),
                            SizedBox(height: 22.4,),
                            _search,
                            loadMoreRestaurants ? Container() : _resNumber,
                            _covidNotification,
                            Padding(
                              padding:
                              const EdgeInsets.only(
                                  left: 20.0, right: 20.0, top: 10.0),
                              child: Text(
                                "Search Result...",
                                style: TextStyle(
                                    fontFamily: "Sofia",
                                    color: Colors.white,
                                    fontSize: 20.0),
                              ),
                            ),
                            searchLoadImage
                                ? _loadingSearchRestaurantsList(context)
                                : Container(
                              child: ListView.builder(
                                padding: EdgeInsets.only(top: 5.0),
                                shrinkWrap: true,
                                primary: false,
                                itemBuilder: (ctx, index) {
                                  List<String> categoryList = List<String>();
                                  categoryList.clear();
                                  for (int i = 0;
                                  i < searchMap['data'][index]['categories']
                                      .length;
                                  i++) {
                                    categoryList.add(
                                        searchMap['data'][index]['categories'][i]['name']);
                                  }
                                  print(categoryList.toString());

                                  return SearchRestaurantsItem(
                                    restaurantId: searchMap['data'][index]['id'],
                                    image: searchMap['data'][index]['images'][0]['url'],
                                    title: searchMap['data'][index]['name'],
                                    // category: 'Categories',
                                    index: index,
                                    category: categoryList
                                        .toString()
                                        .replaceAll("[", "")
                                        .replaceAll("]", ""),
                                    map: searchMap,
                                    location: searchMap['data'][index]['address'],
                                    discount: searchMap['data'][index]['discount'],
                                    rating: searchMap['data'][index]['rating']
                                        .toString(),
                                    ratingCount: searchMap['data'][index]['rating_count']
                                        .toString(),
                                    isFavorite: searchMap['data'][index]['favourite'],
                                    delivery: searchMap['data'][index]['delivery_available'],
                                  );
                                },
                                itemCount: searchMapData.length,
                              ),
                            ),
                          ],
                        ),
                      ],
                    )),
              )
                  : PaginationView<RestaurantDetails>(
                key: key,
                paginationViewType: paginationViewType,
                itemBuilder: (BuildContext context, RestaurantDetails restaurantDetails, int index) {
                  print(restaurantDetails.categoryList);
                  List<String> categoryList = List<String>();
                  categoryList.clear();
                  for (int i = 0;
                  i <
                      restaurantDetails.categoryList.length;
                  i++) {
                    categoryList.add(restaurantDetails.categoryList[i]['name']);
                  }
                  print(categoryList.toString());
                  return  GestureDetector(
                    onTap: () async {
                      //FocusManager.instance.primaryFocus?.unfocus();
                      imageList.clear();
                      for (int i = 0;
                      i < restaurantDetails.imageList.length;
                      i++) {
                        imageList.add(restaurantDetails.imageList[i]['url']);
                      }
                      print(imageList.toString());
                      print(restaurantDetails.id);
                      print(restaurantDetails.restaurantId.toString());
                      print(restaurantDetails.ratingCount);
                      print(restaurantDetails.index);
                      await
                      pushNewScreen(
                          context,
                          withNavBar: false,
                          screen:
                          new DetailFoodScreenT1(
                              title: restaurantDetails.title,
                              id:  restaurantDetails.id,
                              image: restaurantDetails.image,
                              restaurantId: restaurantDetails.restaurantId,
                              imageList: imageList,
                              categoryList: [categoryList
                                  .toString()
                                  .replaceAll("[", "")
                                  .replaceAll("]", "")],
                              timingsList: restaurantDetails.timingsList,
                              phoneNumber: restaurantDetails.phoneNumber,
                              description: restaurantDetails.description,
                              igtv: restaurantDetails.igtv,
                              lat: lat.toString(),
                              lng: long.toString(),
                              rating: restaurantDetails.rating,
                              isFavorite: restaurantDetails.isFavorite,
                              doesDelivery: restaurantDetails.doesDelivery,
                              isSubscribed: restaurantDetails.isSubscribed,
                              ratingCount: restaurantDetails.ratingCount,
                              discount: restaurantDetails.discount,
                              address: restaurantDetails.location,
                              map: moreRestaurantsMap,
                              index: index,
                              isOpen: restaurantDetails.isOpen),
                          pageTransitionAnimation: PageTransitionAnimation.cupertino
                      );

                      SharedPreferences preferences = await SharedPreferences.getInstance();
                      if ((preferences.getString('isFavouriteId') != null) && (preferences.getBool('isFavourite') != null)) {
                        setState(() {
                          isFavourite = preferences.getBool('isFavourite');
                          // onIsFavouritePress(preferences.getString('isFavouriteId'));
                          preferences.remove('isFavourite');
                          preferences.remove('isFavouriteId');
                        });
                      }
                    },
                    child: Padding(
                      padding: const EdgeInsets.only(left: 2.0, top: 10.0),
                      child: Container(
                        decoration: BoxDecoration(
                            color: Color(0xFF23252E),
                            borderRadius: BorderRadius.all(Radius.circular(10.0)),
                            boxShadow: [
                              BoxShadow(
                                color: Color(0xFF656565).withOpacity(0.15),
                                blurRadius: 4.0,
                                spreadRadius: 1.0,
                              )
                            ]),
                        child: Wrap(
                          children: <Widget>[
                            Padding(
                              padding:
                              const EdgeInsets.symmetric(horizontal: 0.0, vertical: 5.0),
                              child: Row(
                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                children: [
                                  Row(
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    mainAxisAlignment: MainAxisAlignment.spaceAround,
                                    mainAxisSize: MainAxisSize.min,
                                    children: <Widget>[
                                      restaurantDetails.discount ==  ""
                                          ? Container(
                                        height: 100.0,
                                        width: 100.0,
                                        decoration: BoxDecoration(
                                          borderRadius: BorderRadius.only(
                                              topLeft: Radius.circular(7.0),
                                              topRight: Radius.circular(7.0)),
                                          image: DecorationImage(
                                              image: CachedNetworkImageProvider(
                                                restaurantDetails.image,
                                                errorListener: () =>
                                                new Icon(Icons.error),
                                              ),
                                              fit: BoxFit.cover),
                                        ),
                                      )
                                          : Container(
                                        height: 100.0,
                                        width: 100.0,
                                        decoration: BoxDecoration(
                                          borderRadius: BorderRadius.only(
                                              topLeft: Radius.circular(7.0),
                                              topRight: Radius.circular(7.0)),
                                          image: DecorationImage(
                                              image: CachedNetworkImageProvider(
                                                restaurantDetails.image,
                                                errorListener: () =>
                                                new Icon(Icons.error),
                                              ),
                                              fit: BoxFit.cover),
                                        ),
                                        child: Column(
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            Container(
                                              height: 15.0,
                                              width: 55.0,
                                              alignment: Alignment.topLeft,
                                              decoration: BoxDecoration(
                                                  color: Constants.mfaRed,
                                                  borderRadius: BorderRadius.only(
                                                      bottomRight:
                                                      Radius.circular(20.0),
                                                      topLeft: Radius.circular(5.0))),
                                              child: Center(
                                                  child: Text(
                                                    restaurantDetails.discount,
                                                    style: TextStyle(
                                                        fontSize: 10.0,
                                                        color: Colors.white,
                                                        fontWeight: FontWeight.w600),
                                                  )),
                                            ),
                                          ],
                                        ),
                                      ),
                                      Padding(padding: EdgeInsets.only(top: 15.0)),
                                      Column(
                                        mainAxisAlignment: MainAxisAlignment.start,
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        children: [
                                          Padding(
                                            padding: const EdgeInsets.only(
                                                left: 15.0, right: 15.0),
                                            child: Text(
                                              restaurantDetails.title,
                                              style: TextStyle(
                                                  color: Colors.white,
                                                  fontFamily: "Sofia",
                                                  fontWeight: FontWeight.w600,
                                                  fontSize: 14),
                                            ),
                                          ),
                                          Padding(padding: EdgeInsets.only(top: 1.0)),
                                          Padding(
                                            padding: const EdgeInsets.only(
                                                left: 15.0, right: 15.0),
                                            child: Text(
                                              restaurantDetails.categoryList.length == 1
                                                  ? restaurantDetails.categoryList[0]['name'].toString()
                                                  : restaurantDetails.categoryList.length == 2
                                                  ? restaurantDetails.categoryList[0]['name'].toString() + ", " +
                                                  restaurantDetails.categoryList[1]['name'].toString()
                                                  : restaurantDetails.categoryList.length == 3
                                                  ? restaurantDetails.categoryList[0]['name'].toString() + ", " +
                                                  restaurantDetails.categoryList[1]['name'].toString() + ", " +
                                                  restaurantDetails.categoryList[2]['name'].toString()
                                                  : restaurantDetails.categoryList[0]['name'].toString() + ", " +
                                                  restaurantDetails.categoryList[1]['name'].toString() + ", " +
                                                  restaurantDetails.categoryList[2]['name'].toString() //+ "..& more"
                                              ,
                                              overflow: TextOverflow.clip,
                                              style: TextStyle(
                                                  letterSpacing: 0.5,
                                                  color: Colors.grey,
                                                  fontFamily: "Sofia",
                                                  fontWeight: FontWeight.w500,
                                                  fontSize: 12.0),
                                            ),
                                          ),
                                          Padding(padding: EdgeInsets.only(top: 1.0)),
                                          Padding(
                                            padding: const EdgeInsets.only(
                                                left: 15.0, right: 15.0),
                                            child: Text(
                                              restaurantDetails.location.length > 20
                                                  ? restaurantDetails.location.replaceRange(
                                                  20, restaurantDetails.location.length, '...')
                                                  : restaurantDetails.location,
                                              overflow: TextOverflow.ellipsis,
                                              style: TextStyle(
                                                // letterSpacing: 0.5,
                                                  color: Colors.white70,
                                                  fontFamily: "Sofia",
                                                  fontWeight: FontWeight.w500,
                                                  fontSize: 13.0),
                                            ),
                                          ),
                                          Padding(
                                            padding: const EdgeInsets.only(
                                                left: 15.0, right: 15.0, top: 5.0),
                                            child: Row(
                                              crossAxisAlignment: CrossAxisAlignment.start,
                                              mainAxisAlignment:
                                              MainAxisAlignment.spaceBetween,
                                              children: <Widget>[
                                                Row(
                                                  children: <Widget>[
                                                    StarRating(
                                                      size: 15.0,
                                                      starCount: 1,
                                                      rating: double.parse(restaurantDetails.rating),
                                                      color: Colors.yellow,
                                                    ),
                                                    Padding(
                                                      padding: const EdgeInsets.only(
                                                          top: 2.0, left: 4),
                                                      child: Text(
                                                        restaurantDetails.rating.length > 1
                                                            ? restaurantDetails.rating.substring(0, 3)
                                                            : restaurantDetails.rating,
                                                        style: TextStyle(
                                                            fontFamily: "Sofia",
                                                            color: Colors.white60,
                                                            fontWeight: FontWeight.w500,
                                                            fontSize: 12.0),
                                                      ),
                                                    ),
                                                    SizedBox(width: 5.0),
                                                    Padding(
                                                      padding:
                                                      const EdgeInsets.only(top: 1.0),
                                                      child: Text("(${restaurantDetails.ratingCount} Reviews)",
                                                        style: TextStyle(
                                                            fontFamily: "Sofia",
                                                            color: Colors.white60,
                                                            fontWeight: FontWeight.w500,
                                                            fontSize: 12.0),
                                                      ),
                                                    )
                                                  ],
                                                ),
                                              ],
                                            ),
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  Align(
                                    alignment: Alignment.centerRight,
                                    child: Padding(
                                      padding: const EdgeInsets.only(left: 20.0),
                                      child: Column(
                                        children: <Widget>[
                                          Padding(
                                            padding:
                                            const EdgeInsets.only(left: 10.0, right: 8.0),
                                            child: !restaurantDetails.isFavorite
                                                ? Container()
                                                : CircleAvatar(
                                              backgroundColor: Colors.white,
                                              radius: 15,
                                              child: IconButton(
                                                  icon: Icon(
                                                    Icons.favorite,
                                                    color: Constants.mfaRed,
                                                    size: 15,
                                                  ),
                                                  onPressed: null),
                                            ),
                                          ),
                                          restaurantDetails.discount == ""
                                              ? Container()
                                              : Container(
                                            height: 25.5,
                                            width: 75.0,
                                            decoration: BoxDecoration(
                                                color: Constants.mfaRed,
                                                borderRadius: BorderRadius.only(
                                                    bottomRight: Radius.circular(20.0),
                                                    topLeft: Radius.circular(5.0))),
                                            child: Center(
                                                child: Text(
                                                  restaurantDetails.discount,
                                                  style: TextStyle(
                                                      color: Colors.white,
                                                      fontWeight: FontWeight.w600),
                                                )),
                                          ),
                                        ],
                                      ),
                                    ),
                                  )
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  );
                },
                pageFetch:
                // !isMoreListLoading ? pageFetchEmpty :
                isEnabled ? pageFetchWithLocation : pageFetch,
                header:
                GestureDetector(
                  onTap: () {
                    FocusScope.of(context).requestFocus(new FocusNode());
                  },
                  child: SingleChildScrollView(
                    physics: BouncingScrollPhysics(),
                    child: Stack(
                      children: <Widget>[
                        _background,
                        // _appBar,
                        Align(
                          alignment: Alignment.centerRight,
                          child: Padding(
                            padding: const EdgeInsets.only(
                                top: 47.0, left: 10.0, right: 0),
                            child: Row(
                                mainAxisAlignment:
                                MainAxisAlignment.spaceBetween,
                                children: <Widget>[
                                  Expanded(
                                    child: Container(
                                      width: MediaQuery
                                          .of(context)
                                          .size
                                          .width,
                                      child: Row(
                                        mainAxisAlignment: MainAxisAlignment
                                            .start,
                                        children: [
                                          Padding(
                                            padding: const EdgeInsets.only(
                                                bottom: 6.0, right: 8),
                                            child: Icon(
                                              Icons.location_on_rounded,
                                              size: 25,
                                              color: Colors.white,
                                            ),
                                          ),
                                          GestureDetector(
                                              onTap: () {
                                                FocusManager.instance
                                                    .primaryFocus?.unfocus();
                                                _editDeliveryLocationModalSheet(
                                                    context);
                                              },
                                              child: //currentPosition != null &&
                                              currentLocation == null || currentLocation ==''
                                                  ? Text(
                                                'Set Your Location',
                                                style: TextStyle(
                                                    fontFamily: "Sofia",
                                                    fontSize: 14,
                                                    // letterSpacing: 1.5,
                                                    color: Colors.white),

                                              )
                                                  : Container(
                                                width: MediaQuery.of(context).size.width * 0.85,
                                                child: Text(
                                                  currentLocation,
                                                  overflow: TextOverflow
                                                      .ellipsis,
                                                  style: TextStyle(
                                                      fontFamily: "Sofia",
                                                      fontSize: 14,
                                                      // letterSpacing: 1.5,
                                                      color: Colors.white),
                                                ),
                                              )
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                ]),
                          ),
                        ),
                        _body,
                      ],
                    ),
                  ),
                ),
                shrinkWrap: true,
                physics: CustomScrollPhysics(),
                pullToRefresh: true,
                onError: (dynamic error) =>
                    Center(
                      child: Text('Some error occured'),
                    ),
                onEmpty: Center(
                  child: Text('Sorry! This is empty'),
                ),
                bottomLoader: Center(
                  child: Padding(
                    padding: const EdgeInsets.only(top: 20.0, bottom: 10),
                    child: CircularProgressIndicator(
                      valueColor:
                      AlwaysStoppedAnimation<Color>(Constants.mfaRed),
                    ),
                  ),
                ),
                initialLoader: ListView(
                  shrinkWrap: true,
                  children: [
                    SizedBox(height: 45),
                    _loadingFeaturedImageCarousel(context),
                    SizedBox(height: 15),
                    Container(
                        height: 80, child: _loadingBrowseByCuisineList(context)),
                    // _loadingImageAnimationDiscount(context),
                    _loadingMoreRestaurantsList(context),
                  ],
                ),
              ),
            ),
          )),
    );`
