### ISSUE TITLE
showing previous loaded data not refresh list

### ISSUE THREAD

**Issue by diwakarguptathb** [excogitatr/pagination_view#54]
showing previous loaded data not refresh list.

**Comment by anggaaryas** [comment]
What do you mean?

**Comment by diwakarguptathb** [comment]
pagination list show previous loaded data. GlobalKey store previous state and not show new response list data from api.mai  thin how can clear paginationview state.

**Comment by anggaaryas** [comment]
just change the key too. it will be rebuild to new data

**Comment by diwakarguptathb** [comment]
Please explain.
here is my code:
 GlobalKey<PaginationViewState> key;

@override
  void initState() {
    // TODO: implement initState
    super.initState();
    key = GlobalKey<PaginationViewState>();
 
  }

 PaginationView<
                                                  ReferralPatientReferrals>(
                                                  key: key,
                                                  //  header: Text('Header text'),
                                                  // footer: Text('Footer text'),
                                                  preloadedItems:
                                                      displayListEmpty,
                                                  paginationViewType:
                                                      PaginationViewType
                                                          .listView,
                                                  itemBuilder: (BuildContext
                                                              context,
                                                          ReferralPatientReferrals
                                                              queryNoters,
                                                          int index) =>
                                                      patientCard(queryNoters),
                                                  pageFetch: pageFetch,
                                                  pullToRefresh: false,
                                                  onError: (dynamic error) =>
                                                      Center(
                                                    child: Text(
                                                        'Some error occured'),
                                                  ),
                                                  onEmpty: Center(
                                                    child: Text(
                                                        'Sorry! This is empty'),
                                                  ),
                                                  bottomLoader: Center(
                                                    child:
                                                        CircularProgressIndicator(),
                                                  ),
                                                  initialLoader: Center(
                                                    child:
                                                        CircularProgressIndicator(),
                                                  ),
                                                )

**Comment by anggaaryas** [comment]
1. make sure that the `pageFetch` method can retrieve new data .
2. if you want to reload list with new data / change data, you should use different `key` . maybe like every time you want to rebuild, you should call `key = GlobalKey` again

**Comment by vedartm** [comment]
Hope your issue is resolved @diwakarguptathb. Thanks for using the package 🎉 . Feel free to reopen this if you this.
